### ISSUE TITLE
Training setting

### ISSUE THREAD

**Issue by lxtGH** [jytime/Mask_RCNN_Pytorch#1]
Hi!! Nice work! Could you share your training setting to reproduce your model

**Comment by lxtGH** [comment]
Can it support multi-gpu training? I didn't see DataParallel in the repo

**Comment by lxtGH** [comment]
@jytime Also how many image you evaluate to get that score ?? The model you provided is the same with the origin reop and this should have the same result. 0.347

**Comment by jytime** [comment]
@lxtGH Sorry I just noticed this. My training model starts from the provided pre-trained model. If I remember correctly (cause recently I am working on other tasks), lr=0.001, batchsize=4, and steps=1000.
After 'training network heads' for 5 epochs,  'finetuning layers from ResNet stage 4 and up' for 10 epochs, and 'finetuning all layers' for 80 epochs, I reached the result. I evaluated the model on 500 COCO images. If you could not reproduce the result, please let me know. Cheers

**Comment by jytime** [comment]
for multi-gpu training, you could refer to the [codes](https://github.com/jytime/Mask_RCNN_Pytorch/blob/2291627add6e5a955be3466e93caa49a8903931b/synthia.py#L278)(line 278) in synthia.py
Sometimes I am not available, but please feel free to ask any question XD
