### ISSUE TITLE
Run demo_coco.py appear Cuda out of memory

### ISSUE THREAD

**Issue by InstantWindy** [jytime/Mask_RCNN_Pytorch#10]
Hi! Does it take up a lot of memory to test demo_coco files?I don't know that every time I run this file there is always a Cuda out of memory. Thanks!

**Comment by jytime** [comment]
hi
it will occupy around 10 GB. Please notice the settings if it reports 'out of memory'

**Comment by InstantWindy** [comment]
Can I ask you a question？When my convolution kernel value is only 1 and -1 or when my input value is only 1 and -1, will the network run faster?

**Comment by jytime** [comment]
It's a bit weird. Do you mean change the kernel size? If so, you have to re-design the network architecture and cannot use the pretrained model.
