### ISSUE TITLE
No pretrained model for demo_synthia

### ISSUE THREAD

**Issue by rkosti** [jytime/Mask_RCNN_Pytorch#4]
Hi, Is it possible to share the trained model on synthia?

**Comment by jytime** [comment]
Hi, you can simply get the model from the 'synthia.py', i.e., fine-tuning the provided model on the SYNTHIA dataset

**Comment by rkosti** [comment]
Yes, but i wanted to test some sample images on your trained model to see the performance. I guess I will have to train it. 
Thanks

**Comment by rkosti** [comment]
Hi, so I started training on synthia using a batchSize of 4. However, I am running out out of memory in the first epoch it'self! 
I tried used the batchSize of 2  along with DataParallelism (as instructed in the [code](https://github.com/jytime/Mask_RCNN_Pytorch/blob/2291627add6e5a955be3466e93caa49a8903931b/synthia.py#L278)), still getting the same error. 

I observe that the code throws this error when it is calculating  `bbox_overlaps` inside `detection_target_layer`. I [shared](https://www.dropbox.com/s/74orw5k3enb5ybi/error.png?dl=0) the screenshot of the whole error. 
Don't understand why this is happening.... 
Could you help here?

**Comment by jytime** [comment]
hi rkosti
Would you like to share your gpu memory? I trained it by a gpu with the memory of around 11Gb

**Comment by rkosti** [comment]
Yes, I am training it on a 'GeForce GTX TITAN X' with 12GB memory. 
There is no other process running on it...

**Comment by jytime** [comment]
In which training stage does the error appear?
Please try to comment the second and third [training stages](https://github.com/jytime/Mask_RCNN_Pytorch/blob/b0f82ba9a4e7b52e638b13bc0105c19351bf8eda/synthia.py#L324) and see the results. Therefore, the model will only fine-tune the heads. If nothing goes wrong, it will require less than 1Gb. If you do not change other parts and this setting does not work, I guess there may be something different in the environment.

I really hope to help you but I cannot access the server recently.

**Comment by rkosti** [comment]
This error occurs in the first stage it'self. I commented the 2nd, 3rd stages. But as you can see, the error is happening in the first stage it'self, so commenting doesn't matter. 
Btw, I am using pytorch 0.3.0.post4, could this be the source of the problem?

**Comment by jytime** [comment]
It should not be because this implementation supports both 0.3.0 and 0.4.0. But you could try it.

**Comment by rkosti** [comment]
I still don't know why it was showing out of memory error. I re-forked your repo and was able to run it without any issues. I didn't even need to use DataParallelism; with a batchSize of 8 and 3 target classes, it occupied ~1.5GB of GPU memory. 
Thanks for the help!
