### ISSUE TITLE
multi-GPU fail

### ISSUE THREAD

**Issue by qiuhaining** [jytime/Mask_RCNN_Pytorch#8]
I cannot use multi-GPU , et  "CUDA_VISIBLE_DEVICES=0,1,2,3" but just device 0 can be seen !

**Comment by jytime** [comment]
Have you looked at the instructions [here](https://github.com/jytime/Mask_RCNN_Pytorch/blob/05053cbd00d1dde2ae7edd59f276d1560ce9fe1f/synthia.py#L278)?
If you have, plz verified if your environment is consistent with the requirements. If you are sure that you have done these well and still cannot use multi-GPU, plz look at [this discussion](https://discuss.pytorch.org/t/while-using-nn-dataparallel-only-accessing-one-gpu/19807/15).
